version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      # .env should be in the same directory as `docker-compose.yml`
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
